/**
 * SOUL 注入器
 *
 * 负责将 SOUL 注入到 System Prompt、检查边界、调整输出风格
 */

import type {
  SoulInjector,
  Soul,
  SoulLoader,
  BoundaryCheck
} from './types.js';
import type { Logger } from '../core/logger/index.js';

/**
 * SOUL 注入器实现
 */
export class SoulInjectorImpl implements SoulInjector {
  private globalSoul: Soul | null = null;
  private agentSouls: Map<string, Soul> = new Map();
  private lastLoad = 0;
  private readonly loadInterval = 60000; // 1分钟

  constructor(
    private soulLoader: SoulLoader,
    _logger: Logger
  ) {}

  /**
   * 将 SOUL 注入到 System Prompt
   */
  async injectToPrompt(agentType: string, basePrompt: string): Promise<string> {
    const souls = await this.loadSouls(agentType);
    const globalSoul = souls.global;
    const agentSoul = souls.agent;

    if (!globalSoul) {
      return basePrompt;
    }

    const soulSection = this.buildSoulSection(globalSoul, agentSoul);
    return `${basePrompt}\n\n${soulSection}`;
  }

  /**
   * 检查操作是否符合 SOUL 边界
   */
  async checkBoundary(agentType: string, action: string): Promise<BoundaryCheck> {
    const souls = await this.loadSouls(agentType);
    const soul = souls.agent || souls.global;

    if (!soul) {
      return { allowed: true };
    }

    // 检查外部操作边界
    const externalActions = ['write', 'delete', 'send', 'post', 'publish'];
    const isExternal = externalActions.some(a => action.toLowerCase().includes(a));

    if (isExternal) {
      const confirmBoundary = soul.boundaries.find(b => b.name === '确认原则');
      if (confirmBoundary && confirmBoundary.enforcement === 'strict') {
        return {
          allowed: true,
          boundary: confirmBoundary,
          reason: '外部操作需要用户确认',
          requiresConfirmation: true
        };
      }
    }

    // 检查隐私边界
    const privateActions = ['email', 'password', 'token', 'secret', 'key'];
    const isPrivate = privateActions.some(a => action.toLowerCase().includes(a));

    if (isPrivate) {
      const privacyBoundary = soul.boundaries.find(b => b.name === '隐私红线');
      if (privacyBoundary) {
        return {
          allowed: false,
          boundary: privacyBoundary,
          reason: '涉及敏感信息，操作被阻止'
        };
      }
    }

    return { allowed: true };
  }

  /**
   * 根据 SOUL 调整输出风格
   */
  async adjustOutput(agentType: string, output: string): Promise<string> {
    const souls = await this.loadSouls(agentType);
    const soul = souls.agent || souls.global;

    if (!soul) {
      return output;
    }

    let adjusted = output;

    // 简洁原则：删除冗余内容
    if (soul.coreTruths.some(t => t.principle.includes('简洁'))) {
      adjusted = this.applyConciseStyle(adjusted);
    }

    // CodeWriter 特殊处理：不添加额外注释
    if (agentType.toLowerCase() === 'codewriter') {
      adjusted = adjusted.replace(/\/\/ Generated by.*$/gm, '');
      adjusted = adjusted.replace(/\n\/\/ [A-Z].*$/gm, '');
    }

    return adjusted;
  }

  /**
   * 构建 SOUL 注入文本
   */
  private buildSoulSection(globalSoul: Soul, agentSoul?: Soul | null): string {
    let section = `## 你的灵魂\n\n`;

    section += `### 核心真理\n\n`;
    for (const truth of globalSoul.coreTruths) {
      section += `- **${truth.principle}** ${truth.description || ''}\n`;
    }

    section += `\n### 边界\n\n`;
    for (const boundary of globalSoul.boundaries) {
      section += `- **${boundary.name}**：${boundary.rule}\n`;
    }

    if (globalSoul.vibe) {
      section += `\n### 氛围\n\n${globalSoul.vibe}\n`;
    }

    if (agentSoul) {
      section += `\n## 角色特质\n\n`;
      for (const trait of agentSoul.traits) {
        section += `- **${trait}**\n`;
      }

      if (agentSoul.coreTruths.length > 0) {
        section += `\n### 角色原则\n\n`;
        for (const truth of agentSoul.coreTruths) {
          section += `- **${truth.principle}** ${truth.description || ''}\n`;
        }
      }
    }

    return section;
  }

  /**
   * 应用简洁风格
   */
  private applyConciseStyle(text: string): string {
    // 删除客套话
    const fillerPhrases = [
      '好的，',
      '没问题，',
      '当然，',
      '我来帮您',
      '很高兴为您',
      '我会尽量',
      'Let me',
      'I will',
      'Here is'
    ];

    let lines = text.split('\n');
    lines = lines.filter(line => {
      const lower = line.toLowerCase();
      return !fillerPhrases.some(phrase => lower.startsWith(phrase.toLowerCase()));
    });

    return lines.join('\n');
  }

  /**
   * 加载 SOUL（带缓存）
   */
  private async loadSouls(agentType: string): Promise<{
    global: Soul | null;
    agent: Soul | null;
  }> {
    const now = Date.now();
    if (now - this.lastLoad > this.loadInterval) {
      // 刷新缓存
      this.globalSoul = await this.soulLoader.loadGlobal();
      this.agentSouls.clear();
      this.lastLoad = now;
    }

    const agent = this.agentSouls.get(agentType) ||
      await this.soulLoader.loadAgent(agentType);

    if (agent && !this.agentSouls.has(agentType)) {
      this.agentSouls.set(agentType, agent);
    }

    return {
      global: this.globalSoul || null,
      agent: agent || null
    };
  }
}

/**
 * 创建 SoulInjector 实例
 */
export function createSoulInjector(
  soulLoader: SoulLoader,
  logger: Logger
): SoulInjector {
  return new SoulInjectorImpl(soulLoader, logger);
}
